apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-txplux
  annotations:
    # Use a static ip
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: ip-txplux
    certmanager.k8s.io/issuer: "letsencrypt-dev"
    certmanager.k8s.io/acme-challenge-type: http01
    # enable session persistence for one or multiple services

spec:  
  rules:
  - host: app.txplux.com.co
    http:
      paths:  
      - path: /*
        backend:
          serviceName: web-sample
          servicePort: 8080     
  tls:
      - hosts:
        - app.txplux.com.co
        secretName: tpi-tls-txplux
